// lib/main.dart
//
// MUST StarTrack — Application Entry Point (Phase 5 — Fully Wired)
//
// Boot sequence:
//   1. Flutter bindings
//   2. Lock to portrait orientation
//   3. Set transparent status bar
//   4. Firebase.initializeApp() with platform-specific options
//   5. InjectionContainer.init() — registers all dependencies
//   6. AuthCubit.checkAuthStatus() — resolves persisted session
//   7. FcmService.init() — sets up push notification handlers
//   8. runApp(StarTrackApp())
//
// Panel defence:
//   "We initialise Firebase before get_it so FirebaseAuth.instance
//    and FirebaseFirestore.instance are available when we register
//    them as singletons. AuthCubit.checkAuthStatus() is called here,
//    not in SplashScreen, so the session is resolved before the first
//    frame paints. FcmService.init() registers the background message
//    handler which must be a top-level function — a Firebase requirement."
//
// Note on firebase_options.dart:
//   Generated by: flutterfire configure --project=must-startrack
//   See firebase_options.dart for the template.

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:firebase_core/firebase_core.dart';

import 'firebase_options.dart';
import 'app/app.dart';
import 'core/di/injection_container.dart';
import 'features/auth/bloc/auth_cubit.dart';

Future<void> _ensureFirebaseInitialized() async {
  if (Firebase.apps.isNotEmpty) {
    return;
  }

  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } on FirebaseException catch (e) {
    // Android may auto-create [DEFAULT] via FirebaseInitProvider.
    if (e.code != 'duplicate-app') {
      rethrow;
    }
  }
}

Future<void> main() async {
  // ── Step 1: Flutter binding ───────────────────────────────────────────────
  WidgetsFlutterBinding.ensureInitialized();

  // ── Step 2: Portrait lock ─────────────────────────────────────────────────
  // Academic app — portrait-only for focused reading and form entry.
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  // ── Step 3: System UI (transparent status bar) ────────────────────────────
  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      statusBarIconBrightness: Brightness.dark,
      systemNavigationBarColor: Colors.transparent,
      systemNavigationBarIconBrightness: Brightness.dark,
    ),
  );

  // Enable edge-to-edge rendering (Android 15+)
  SystemChrome.setEnabledSystemUIMode(SystemUiMode.edgeToEdge);

  // ── Step 4: Firebase ──────────────────────────────────────────────────────
  // DefaultFirebaseOptions is generated by `flutterfire configure`.
  // Run: flutterfire configure --project=must-startrack-[your-id]
  await _ensureFirebaseInitialized();

  // ── Step 5: Dependency injection ──────────────────────────────────────────
  await InjectionContainer.init();

  // ── Step 6: Auth session check ────────────────────────────────────────────
  // Resolves immediately from SQLite if a session is cached.
  // SplashScreen listens for the result and navigates accordingly.
  await sl<AuthCubit>().checkAuthStatus();

  // ── Step 7: Launch app ────────────────────────────────────────────────────
  runApp(const StarTrackApp());
}
