// lib/main.dart
//
// MUST StarTrack — Application Entry Point (Phase 5 — Fully Wired)
//
// Boot sequence:
//   1. Flutter bindings
//   2. Lock to portrait orientation
//   3. Set transparent status bar
//   4. Firebase.initializeApp() with platform-specific options
//   5. InjectionContainer.init() — registers all dependencies
//   6. AuthCubit.checkAuthStatus() — resolves persisted session
//   7. FcmService.init() — sets up push notification handlers
//   8. runApp(StarTrackApp())
//
// Panel defence:
//   "We initialise Firebase before get_it so FirebaseAuth.instance
//    and FirebaseFirestore.instance are available when we register
//    them as singletons. AuthCubit.checkAuthStatus() is called here,
//    not in SplashScreen, so the session is resolved before the first
//    frame paints. FcmService.init() registers the background message
//    handler which must be a top-level function — a Firebase requirement."
//
// Note on firebase_options.dart:
//   Generated by: flutterfire configure --project=must-startrack
//   See firebase_options.dart for the template.

import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:firebase_core/firebase_core.dart';

import 'firebase_options.dart';
import 'app/app.dart';
import 'core/di/injection_container.dart';
import 'core/services/session_timeout_service.dart';
import 'features/auth/bloc/auth_cubit.dart';
import 'features/ai/screens/web_recommendation_shell.dart';

void _logBoot(String step, [Map<String, Object?> details = const {}]) {
  debugPrint('[Boot][$step] ${details.isEmpty ? '' : details}');
}

Future<void> _ensureFirebaseInitialized() async {
  if (Firebase.apps.isNotEmpty) {
    _logBoot('firebase_already_initialized', {
      'appCount': Firebase.apps.length,
    });
    return;
  }

  try {
    _logBoot('firebase_init_started');
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    _logBoot('firebase_init_completed');
  } on FirebaseException catch (e) {
    // Android may auto-create [DEFAULT] via FirebaseInitProvider.
    if (e.code != 'duplicate-app') {
      _logBoot('firebase_init_failed', {
        'code': e.code,
        'message': e.message ?? '',
      });
      rethrow;
    }
    _logBoot('firebase_duplicate_app_ignored', {
      'code': e.code,
    });
  }
}

Future<void> main() async {
  // ── Step 1: Flutter binding ───────────────────────────────────────────────
  WidgetsFlutterBinding.ensureInitialized();
  _logBoot('bindings_ready', {
    'platform': kIsWeb ? 'web' : defaultTargetPlatform.name,
  });

  if (kIsWeb) {
    _logBoot('web_mode_entered', {
      'scope': 'recommendation_only',
    });
    // Firebase must be initialised before the app accesses
    // FirebaseAuth.instance or FirebaseFirestore.instance.
    await _ensureFirebaseInitialized();
    await InjectionContainer.initWeb();
    runApp(const StarTrackWebRecommendationsApp());
    return;
  }

  // ── Step 2: Portrait lock ─────────────────────────────────────────────────
  // Academic app — portrait-only for focused reading and form entry.
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);
  _logBoot('orientation_locked');

  // ── Step 3: System UI (transparent status bar) ────────────────────────────
  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      statusBarIconBrightness: Brightness.dark,
      systemNavigationBarColor: Colors.transparent,
      systemNavigationBarIconBrightness: Brightness.dark,
    ),
  );

  // Enable edge-to-edge rendering (Android 15+)
  SystemChrome.setEnabledSystemUIMode(SystemUiMode.edgeToEdge);
  _logBoot('system_ui_configured');

  // ── Step 4: Firebase ──────────────────────────────────────────────────────
  // DefaultFirebaseOptions is generated by `flutterfire configure`.
  // Run: flutterfire configure --project=must-startrack-[your-id]
  await _ensureFirebaseInitialized();

  // ── Step 5: Dependency injection ──────────────────────────────────────────
  _logBoot('di_init_started');
  await InjectionContainer.init();
  _logBoot('di_init_completed');

  // ── Step 6: Auth session check ────────────────────────────────────────────
  // Resolves immediately from SQLite if a session is cached.
  // SplashScreen listens for the result and navigates accordingly.
  _logBoot('auth_check_started');
  await sl<AuthCubit>().checkAuthStatus();
  _logBoot('auth_check_completed', {
    'state': sl<AuthCubit>().state.runtimeType.toString(),
  });

  // ── Step 6b: Expire stale sessions before first frame ─────────────────────
  // If the app was restarted and the last recorded activity is older than
  // the background timeout threshold, sign out before rendering anything.
  // This prevents ghost sessions from surviving device restarts.
  if (sl<AuthCubit>().state is AuthAuthenticated &&
      sl<SessionTimeoutService>().isStale()) {
    _logBoot('stale_session_detected');
    await sl<AuthCubit>().logout();
  }

  // ── Step 7: Launch app ────────────────────────────────────────────────────
  _logBoot('run_app_native');
  runApp(const StarTrackApp());
}
